-- Copyright (c) 2012 GFT Appverse, S.L., Sociedad Unipersonal.
--
-- This Source Code Form is subject to the terms of the Appverse Public License 
-- Version 2.0 (“APL v2.0”). If a copy of the APL was not distributed with this 
-- file, You can obtain one at http://www.appverse.mobi/licenses/apl_v2.0.pdf. [^]
--
-- Redistribution and use in source and binary forms, with or without modification, 
-- are permitted provided that the conditions of the AppVerse Public License v2.0 
-- are met.
--
-- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
-- ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
-- WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
-- DISCLAIMED. EXCEPT IN CASE OF WILLFUL MISCONDUCT OR GROSS NEGLIGENCE, IN NO EVENT
-- SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
-- INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
-- LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
-- PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
-- WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT(INCLUDING NEGLIGENCE OR OTHERWISE) 
-- ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
-- POSSIBILITY OF SUCH DAMAGE.

CREATE TABLE USER (ID BIGINT NOT NULL, ACTIVE BOOLEAN NOT NULL, CREATED TIMESTAMP NOT NULL, CREATED_BY VARCHAR(100) NOT NULL, EMAIL VARCHAR(40) NOT NULL, LASTNAME VARCHAR(40) NOT NULL, NAME VARCHAR(40) NOT NULL, PASSWORD VARCHAR(40) NOT NULL, STATUS VARCHAR(255) NOT NULL, UPDATED TIMESTAMP, UPDATED_BY VARCHAR(100), VERSION BIGINT, PRIMARY KEY (ID));
ALTER TABLE USER ADD CONSTRAINT UNQ_USER_4 UNIQUE (EMAIL);
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT NUMERIC(38), PRIMARY KEY (SEQ_NAME));
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('USER_SEQ', 0);
